// Tamper Monkey Script
// ==UserScript==
// @name         Home Away League Table Collector
// @namespace    http://tampermonkey.net/
// @version      0.1.0
// @description  Extracts data from FootyStats home-away league table pages and displays it in a floating popup.
// @author       Viet Cat (Generated by Gemini)
// @match        https://footystats.org/vn/*/*/home-away-league-table
// @grant        GM_xmlhttpRequest
// @grant        GM.xmlHttpRequest
// @icon         https://www.google.com/s2/favicons?sz=64&domain=footystats.org
// @connect      *
// ==/UserScript==

/**
 * Main script function - wrapped in IIFE for scope isolation
 * This script creates a floating popup to collect and display data from a CSV file.
 * Features:
 * - Finds a CSV download link on the page (needs configuration).
 * - Fetches and parses the CSV data.
 * - Displays data in a dynamic table.
 * - Auto-refresh with configurable intervals.
 * - Manual refresh, pause/resume functionality.
 * - Draggable, resizable, and collapsible UI.
 */
;(function () {
  'use strict'

  try {
    console.log('Home/Away Table Collector: Script starting...')

    // ==================== CONSTANTS ====================
    const CONSTANTS = {
      REFRESH: {
        DEFAULT_INTERVAL: 10,
        NO_DATA_INTERVAL: 5,
        DATA_FOUND_INTERVAL: 60,
      },
      POPUP: {
        DEFAULT_WIDTH: 450,
        MIN_WIDTH: 300,
        MIN_HEIGHT: 200,
        HEADER_HEIGHT: 30,
      },
      COLORS: {
        HEADER_GRADIENT_START: '#005f73',
        HEADER_GRADIENT_END: '#0a9396',
        BACKGROUND: '#f8f9fa',
        BORDER: '#dee2e6',
        HEADER_BACKGROUND: '#e9ecef',
      },
      ANIMATIONS: {
        SPIN_DURATION: 1000,
      },
      REQUEST: {
        TIMEOUT: 30000,
      },
      LOG: {
        MAX_LINES: 500,
      },
      Z_INDEX: 2147483647,
    }

    // ==================== SETTINGS (USER CONFIG) ====================
    const SETTINGS_STORAGE_KEY = 'home_away_table_collector_settings_v1'
    const settings = loadSettings()

    function loadSettings() {
      try {
        const raw = localStorage.getItem(SETTINGS_STORAGE_KEY)
        const parsed = raw ? JSON.parse(raw) : {}

        let reqDelay = parsed.requestDelay
        // Heuristic: if value is large, assume it's old data in ms and convert to s.
        if (reqDelay && Number(reqDelay) >= 1000) {
          console.log(
            `Home/Away Table Collector: Old requestDelay value (${reqDelay}ms) found. Converting to seconds.`
          )
          reqDelay = Number(reqDelay) / 1000
        }

        return {
          defaultInterval:
            Number(parsed.defaultInterval) > 0
              ? Number(parsed.defaultInterval)
              : CONSTANTS.REFRESH.DEFAULT_INTERVAL,
          noDataInterval:
            Number(parsed.noDataInterval) > 0
              ? Number(parsed.noDataInterval)
              : CONSTANTS.REFRESH.NO_DATA_INTERVAL,
          dataFoundInterval:
            Number(parsed.dataFoundInterval) > 0
              ? Number(parsed.dataFoundInterval)
              : CONSTANTS.REFRESH.DATA_FOUND_INTERVAL,
          visibleColumns: Array.isArray(parsed.visibleColumns)
            ? parsed.visibleColumns.filter((value) => typeof value === 'string')
            : null,

        }
      } catch (_) {
        return {
          defaultInterval: CONSTANTS.REFRESH.DEFAULT_INTERVAL,
          noDataInterval: CONSTANTS.REFRESH.NO_DATA_INTERVAL,
          dataFoundInterval: CONSTANTS.REFRESH.DATA_FOUND_INTERVAL,
          visibleColumns: null,

        }
      }
    }

    function saveSettings(newSettings) {
      try {
        localStorage.setItem(SETTINGS_STORAGE_KEY, JSON.stringify(newSettings))
      } catch (_) {}
    }

    // ==================== STATE MANAGEMENT ====================
    const state = {
      timeLeft: settings.defaultInterval,
      refreshIntervalId: null,
      isPaused: false,
      isRefreshing: false,
      currentInterval: settings.defaultInterval,
      isDragging: false,
      isResizing: false,
      isCollapsed: false,
      startX: 0,
      startY: 0,
      startLeft: 0,
      startTop: 0,
      startWidth: 0,
      startHeight: 0,
      originalWidth: CONSTANTS.POPUP.DEFAULT_WIDTH,
      originalHeight: 0,
      lastRequestStartTime: 0, // Timestamp of the last background request start
      lastDataSignature: '',
      lastRecordCount: 0,
      isProcessingUrls: false, // To specifically track this background task
      cancelProcessing: false, // Flag to signal cancellation
      extraHeaders: [], // Stores the keys of extra columns in order
      extraDataByUrl: new Map(), // Runtime extracted data keyed by Match FootyStats URL
      userHasResized: false,
      autoScrollLog: true,
    }

    // ==================== TABLE DATA CONFIGURATION ====================
    function evaluateXPathNodes(xpath, context = document) {
      const ownerDoc = context.ownerDocument || context
      const result = ownerDoc.evaluate(
        xpath,
        context,
        null,
        XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,
        null
      )
      const nodes = []
      for (let i = 0; i < result.snapshotLength; i++) {
        nodes.push(result.snapshotItem(i))
      }
      return nodes
    }

    function findCommonAncestor(nodes) {
      if (!nodes.length) return null

      const getAncestors = (node) => {
        const ancestors = []
        let current = node
        while (current) {
          ancestors.push(current)
          current = current.parentElement
        }
        return ancestors
      }

      const firstAncestors = getAncestors(nodes[0])
      return firstAncestors.find((ancestor) =>
        nodes.every((node) => ancestor === node || ancestor.contains(node))
      )
    }

    function getDirectChildContaining(node, tagName, root) {
      let current = node
      while (current && current.parentElement !== root) {
        current = current.parentElement
      }
      return current && current.tagName === tagName ? current : null
    }

    function getCellText(cell) {
      return String(cell?.textContent || '').replace(/\s+/g, ' ').trim()
    }

    function getDirectText(element) {
      return Array.from(element?.childNodes || [])
        .filter((node) => node.nodeType === Node.TEXT_NODE)
        .map((node) => node.textContent)
        .join(' ')
        .replace(/\s+/g, ' ')
        .trim()
    }

    function getDefaultHeader(originalColumnIndex) {
      if (originalColumnIndex === 16) return 'Thẻ'
      if (originalColumnIndex === 17) return 'Phạt góc'
      return `Cột ${originalColumnIndex + 1}`
    }

    function getTableHeaders(table) {
      const headerRow = table.querySelector('thead tr') || table.querySelector('tr')
      const cells = headerRow
        ? Array.from(headerRow.children).filter((cell) =>
            /^(TH|TD)$/.test(cell.tagName)
          )
        : []

      return cells.slice(2).map((cell, index) => {
        return getDirectText(cell) || getDefaultHeader(index + 2)
      })
    }

    function getTableCellValue(cell, originalColumnIndex) {
      if (originalColumnIndex === 11) {
        return Array.from(cell.querySelectorAll('li a'))
          .map(getCellText)
          .filter(Boolean)
          .join(' ')
      }

      return getCellText(cell)
    }

    function getVisibleColumnKeys(columnMeta = []) {
      const allKeys = columnMeta.map((column) => column.key)
      if (!Array.isArray(settings.visibleColumns)) return allKeys

      const selected = settings.visibleColumns.filter((key) =>
        allKeys.includes(key)
      )
      return selected.length ? selected : allKeys
    }

    function filterExtractedDataColumns(data) {
      const columnMeta = Array.isArray(data.columnMeta) ? data.columnMeta : []
      if (!columnMeta.length) return data

      const visibleKeys = new Set(getVisibleColumnKeys(columnMeta))
      const visibleIndexes = columnMeta
        .map((column, index) => ({ column, index }))
        .filter(({ column }) => visibleKeys.has(column.key))
        .map(({ index }) => index)

      const filtered = data.map((row) => visibleIndexes.map((index) => row[index]))
      filtered.columnMeta = visibleIndexes.map((index) => columnMeta[index])
      filtered.headerGroups = buildHeaderGroups(filtered.columnMeta)
      return filtered
    }

    function buildHeaderGroups(columnMeta = []) {
      const groups = []
      columnMeta.forEach((column) => {
        const title = column.groupTitle || ''
        const last = groups[groups.length - 1]
        if (last && last.title === title) {
          last.colspan++
        } else {
          groups.push({ title, colspan: 1 })
        }
      })
      return groups
    }

    function extractRowsFromTable(table) {
      const bodyRows = table.tBodies.length
        ? Array.from(table.tBodies).flatMap((tbody) => Array.from(tbody.rows))
        : Array.from(table.rows).slice(1)

      return bodyRows
        .map((tr) => {
          const cells = Array.from(tr.children).filter((cell) =>
            /^(TH|TD)$/.test(cell.tagName)
          )
          const dataCells = cells.slice(2)
          const teamId = dataCells[0]
            ?.querySelector('a[data-team-id]')
            ?.getAttribute('data-team-id')
            ?.trim()

          if (!teamId) return null

          return {
            teamId,
            values: dataCells.map((cell, index) =>
              getTableCellValue(cell, index + 2)
            ),
          }
        })
        .filter(Boolean)
    }

    // Trích xuất dữ liệu từ các bảng full-league-table, nối ngang theo data-team-id.
    function extractHomeAwayLeagueTableData(doc = document) {
      const tables = evaluateXPathNodes(
        "//table[contains(@class,'full-league-table')]",
        doc
      )
      if (!tables.length) return [['Status'], ['No full-league-table found.']]

      const dataRoot = findCommonAncestor(tables)
      if (!dataRoot) return [['Status'], ['Data root not found.']]

      const sections = []
      const usedTables = new Set()
      const directChildren = Array.from(dataRoot.children)

      for (let i = 0; i < directChildren.length; i++) {
        const h2 = directChildren[i]
        if (h2.tagName !== 'H2') continue

        const content = directChildren[i + 1]
        const table = content?.querySelector?.('table.full-league-table')
        if (!table) continue

        usedTables.add(table)
        sections.push({
          title: getCellText(h2),
          table,
        })
      }

      // Fallback nếu DOM có wrapper khác với mô tả: vẫn lấy h2/direct div gần nhất của từng table.
      tables.forEach((table) => {
        if (usedTables.has(table)) return
        const tableWrapper = getDirectChildContaining(table, 'DIV', dataRoot)
        const tableIndex = tableWrapper ? directChildren.indexOf(tableWrapper) : -1
        const h2 = tableIndex > 0 ? directChildren[tableIndex - 1] : null
        sections.push({
          title: h2?.tagName === 'H2' ? getCellText(h2) : '',
          table,
        })
      })

      const headers = ['Team ID']
      const columnMeta = [
        {
          key: 'team-id',
          groupTitle: '',
          header: 'Team ID',
          required: true,
        },
      ]
      const rowsByTeamId = new Map()

      sections.forEach(({ title, table }, sectionIndex) => {
        const sectionHeaders = getTableHeaders(table)
        const sectionStartIndex = headers.length - 1
        headers.push(...sectionHeaders)
        sectionHeaders.forEach((header, columnIndex) => {
          columnMeta.push({
            key: `${sectionIndex}:${columnIndex}`,
            groupTitle: title,
            header,
            required: sectionIndex === 0 && columnIndex === 0,
          })
        })

        extractRowsFromTable(table).forEach(({ teamId, values }) => {
          if (!rowsByTeamId.has(teamId)) {
            rowsByTeamId.set(teamId, Array(headers.length - 1).fill(''))
          }

          const row = rowsByTeamId.get(teamId)
          while (row.length < headers.length - 1) row.push('')
          values.forEach((value, index) => {
            row[sectionStartIndex + index] = value
          })
        })

        rowsByTeamId.forEach((row) => {
          while (row.length < headers.length - 1) row.push('')
        })
      })

      const rows = Array.from(rowsByTeamId.entries()).map(([teamId, values]) => [
        teamId,
        ...values,
      ])

      const result = [headers, ...rows]
      result.columnMeta = columnMeta
      result.headerGroups = buildHeaderGroups(columnMeta)
      return result
    }

    // ==================== UTILITY FUNCTIONS ====================
    /**
     * Creates a delay for a specified number of milliseconds.
     * @param {number} ms - The number of milliseconds to wait.
     * @returns {Promise<void>}
     */
    function delay(ms) {
      return new Promise((resolve) => setTimeout(resolve, ms))
    }

    // ==================== PAGE DATA PROCESSING ====================

    // ==================== UI & TABLE FUNCTIONS ====================

    /**
     * Creates a table cell with consistent styling.
     * @param {string} content - Cell content.
     * @returns {HTMLElement} - Styled table cell.
     */
    function createTableCell(content) {
      const td = document.createElement('td')
      td.textContent = content
      td.style.cssText = `
        border: 1px solid ${CONSTANTS.COLORS.BORDER};
        padding: 6px 8px;
        text-align: left;
        white-space: nowrap;
      `
      return td
    }

    /**
     * Updates the popup table with parsed CSV data.
     * @param {Array<Array<string>>} data - Array of rows, where each row is an array of strings.
     * @param {HTMLElement} tbody - Table body element to update.
     */
    function updateTableWithData(data, tbody, force = false) {
      try {
        const signature = JSON.stringify(data)
        if (!force && signature === state.lastDataSignature) {
          window.logToPopup('Data unchanged, skipping table update.')
          return
        }
        state.lastDataSignature = signature

        const table = tbody.closest('table')
        if (!table) return

        const thead = table.querySelector('thead')
        tbody.innerHTML = ''
        thead.innerHTML = ''

        const headers = data && data.length > 0 ? data[0] : []
        if (!data || data.length === 0) {
          tbody.innerHTML = '<tr><td>No data to display.</td></tr>'
          return
        }

        const createHeaderCell = (headerText, fallbackText, top = '0') => {
          const th = document.createElement('th')
          th.textContent = headerText || fallbackText
          th.style.cssText = `
            border: 1px solid ${CONSTANTS.COLORS.BORDER};
            padding: 8px;
            background-color: ${CONSTANTS.COLORS.HEADER_BACKGROUND};
            font-weight: bold;
            text-align: left;
            position: sticky;
            top: ${top};
          `
          return th
        }

        const markGroupBoundaries = (cells, groups) => {
          if (!groups) return
          let offset = 0
          groups.forEach((group, groupIndex) => {
            if (groupIndex > 0 && cells[offset]) {
              cells[offset].style.borderLeft = '3px solid #495057'
            }
            offset += group.colspan || 1
          })
        }

        const headerGroups = Array.isArray(data.headerGroups)
          ? data.headerGroups
          : null
        if (headerGroups) {
          const groupRow = document.createElement('tr')
          headerGroups.forEach((group) => {
            const th = createHeaderCell(group.title || '', '', '0')
            th.colSpan = group.colspan || 1
            th.style.textAlign = 'center'
            th.style.borderLeft = '3px solid #495057'
            th.style.borderRight = '3px solid #495057'
            groupRow.appendChild(th)
          })
          thead.appendChild(groupRow)
        }

        const headerRow = document.createElement('tr')
        headers.forEach((headerText, index) => {
          const th = createHeaderCell(
            headerText,
            `Cột ${index + 1}`,
            headerGroups ? '35px' : '0'
          )
          headerRow.appendChild(th)
        })
        markGroupBoundaries(Array.from(headerRow.children), headerGroups)
        thead.appendChild(headerRow)

        data.slice(1).forEach((rowData) => {
          const tr = document.createElement('tr')
          headers.forEach((_, index) => {
            tr.appendChild(createTableCell(rowData[index] ?? ''))
          })
          markGroupBoundaries(Array.from(tr.children), headerGroups)
          tbody.appendChild(tr)
        })

        window.logToPopup(`Table updated with ${Math.max(data.length - 1, 0)} rows.`)
        adjustPopupWidth()
      } catch (error) {
        console.error('Home/Away Table Collector: Error in updateTableWithData:', error)
        window.logToPopup(`Error updating table: ${error.message}`)
      }
    }

    /**
     * Adjusts popup width based on table content.
     */
    function adjustPopupWidth() {
      if (state.userHasResized) return

      const table = document.querySelector('#csv-collector-popup table')
      if (!table) return

      const popup = document.getElementById('csv-collector-popup')
      if (popup) {
        const rect = popup.getBoundingClientRect()
        // Required width is table's scroll width + padding of mainContent (10px each side).
        const requiredWidth = table.scrollWidth + 20
        // Max width is viewport width minus current left position.
        const maxWidth = window.innerWidth - rect.left

        const newWidth = Math.min(
          Math.max(requiredWidth, CONSTANTS.POPUP.MIN_WIDTH),
          maxWidth
        )
        popup.style.width = `${newWidth}px`
        state.originalWidth = newWidth
      }
    }

    // ==================== REFRESH MANAGEMENT ====================

    /**
     * Tạm dừng auto-refresh, thực thi một hàm async, sau đó tiếp tục refresh.
     * Điều này đảm bảo các tác vụ dài hơi như xử lý tab con không bị gián đoạn.
     * @param {Function} asyncFn - Hàm async để thực thi trong lúc refresh bị tạm dừng.
     */
    async function withRefreshSuspended(asyncFn) {
      if (state.isProcessingUrls) {
        window.logToPopup('URL processing is already running. Skipping duplicate task.')
        return
      }

      const wasAlreadyPaused = state.isPaused
      state.isProcessingUrls = true // Set processing state
      state.cancelProcessing = false // Reset cancellation flag
      if (!wasAlreadyPaused) {
        state.isPaused = true
        if (window.csvCollectorRefreshIndicator) {
          // Cập nhật UI để cho biết một tiến trình đang chạy
          window.csvCollectorRefreshIndicator.textContent = 'Processing URLs...'
        }
        window.logToPopup('Auto-refresh suspended for URL processing.')
      }

      try {
        await asyncFn()
      } catch (error) {
        console.error(
          'Home/Away Table Collector: Error during suspended refresh task:',
          error
        )
        window.logToPopup(`Error during URL processing: ${error.message}`)
      } finally {
        state.isProcessingUrls = false // Reset processing state
        if (!wasAlreadyPaused) {
          state.isPaused = false
          // Reset lại đồng hồ đếm ngược để bắt đầu một chu kỳ mới
          state.timeLeft = state.currentInterval
          if (window.csvCollectorRefreshIndicator) {
            window.csvCollectorRefreshIndicator.textContent = `Auto-refresh in: ${state.timeLeft}s`
          }
          // Check if it was cancelled to log the correct message
          if (state.cancelProcessing) {
            window.logToPopup('Processing cancelled. Auto-refresh resumed.')
          } else {
            window.logToPopup('Auto-refresh resumed.')
          }
        }
        state.cancelProcessing = false // Always reset at the end
      }
    }

    /**
     * Main refresh function - finds CSV, fetches, parses, and updates the table.
     */
    async function refreshData(force = false) {
      if (state.isRefreshing) {
        console.log('Home/Away Table Collector: Skipping refresh - already in progress.')
        return
      }

      try {
        state.isRefreshing = true
        window.logToPopup('Refreshing data from current page...')

        const rawPageData = extractHomeAwayLeagueTableData(document)
        window.homeAwayTableCollectorRawData = rawPageData
        updateColumnSettingsPanel(rawPageData)
        const pageData = filterExtractedDataColumns(rawPageData)
        window.homeAwayTableCollectorLastData = pageData

        if (window.csvCollectorTbody) {
          updateTableWithData(pageData, window.csvCollectorTbody, force)
        }

        const recordCount = pageData.length > 1 ? pageData.length - 1 : 0
        state.lastRecordCount = recordCount
        updateRefreshInterval(recordCount)
        window.logToPopup(
          `Successfully processed ${recordCount} records at ${new Date().toLocaleTimeString()}`
        )
      } catch (error) {
        console.error('Home/Away Table Collector: Error in refreshData:', error)
        window.logToPopup(`Error refreshing data: ${error.message}`)
        updateTableWithData([], window.csvCollectorTbody)
      } finally {
        state.isRefreshing = false
        state.timeLeft = state.currentInterval
        if (window.csvCollectorRefreshIndicator) {
          window.csvCollectorRefreshIndicator.textContent = `Auto-refresh in: ${state.timeLeft}s`
        }
      }
    }

    /**
     * Updates refresh interval based on whether data was found.
     * @param {number} recordCount - Number of data records found (excluding header).
     */
    function updateRefreshInterval(recordCount) {
      if (recordCount === 0) {
        state.currentInterval = settings.noDataInterval
        window.logToPopup(
          `No data found. Refresh interval set to ${state.currentInterval}s`
        )
      } else {
        state.currentInterval = settings.dataFoundInterval
        window.logToPopup(
          `Found ${recordCount} records. Refresh interval set to ${state.currentInterval}s`
        )
      }
    }

    /**
     * Starts the auto-refresh interval.
     */
    function startRefreshInterval() {
      if (state.refreshIntervalId) {
        clearInterval(state.refreshIntervalId)
      }
      state.timeLeft = state.currentInterval
      if (window.csvCollectorRefreshIndicator) {
        window.csvCollectorRefreshIndicator.textContent = `Auto-refresh in: ${state.timeLeft}s`
      }

      state.refreshIntervalId = setInterval(() => {
        if (!state.isPaused) {
          state.timeLeft--
          if (state.timeLeft <= 0) {
            refreshData()
          } else if (window.csvCollectorRefreshIndicator) {
            window.csvCollectorRefreshIndicator.textContent = `Auto-refresh in: ${state.timeLeft}s`
          }
        }
      }, 1000)
    }

    // ==================== POPUP CREATION & EVENT HANDLERS ====================
    // This section is largely adapted from oddsCollector_bwing.js for the UI.

    function setupDragAndDrop(popup, header) {
      const handleMouseDown = (e) => {
        // Cho phép kéo từ nền của header hoặc khu vực tiêu đề.
        // Các cú nhấp chuột vào các nút điều khiển sẽ có target khác
        // và không kích hoạt kéo, đây là hành vi mong muốn.
        if (e.target === header || e.target.closest('.title-container')) {
          state.isDragging = true
          state.startX = e.clientX
          state.startY = e.clientY
          const rect = popup.getBoundingClientRect()
          state.startLeft = rect.left
          state.startTop = rect.top
          e.preventDefault()
        }
      }
      const handleMouseMove = (e) => {
        if (!state.isDragging) return
        const dx = e.clientX - state.startX
        const dy = e.clientY - state.startY

        let newLeft = state.startLeft + dx
        let newTop = state.startTop + dy

        // Đảm bảo popup không bị kéo ra ngoài viewport
        const maxLeft = window.innerWidth - popup.offsetWidth
        const maxTop = window.innerHeight - popup.offsetHeight
        newLeft = Math.max(0, Math.min(newLeft, maxLeft))
        newTop = Math.max(0, Math.min(newTop, maxTop))

        popup.style.left = `${newLeft}px`
        popup.style.top = `${newTop}px`
      }
      const handleMouseUp = () => {
        state.isDragging = false
      }
      header.addEventListener('mousedown', handleMouseDown)
      document.addEventListener('mousemove', handleMouseMove)
      document.addEventListener('mouseup', handleMouseUp)
    }

    function setupResize(popup, resizeHandle) {
      const handleMouseDown = (e) => {
        e.preventDefault()
        state.isResizing = true
        state.startX = e.clientX
        state.startY = e.clientY
        state.startWidth = popup.offsetWidth
        state.startHeight = popup.offsetHeight
      }
      const handleMouseMove = (e) => {
        if (!state.isResizing) return
        const dx = e.clientX - state.startX
        const dy = e.clientY - state.startY

        const rect = popup.getBoundingClientRect()

        // Đảm bảo kích thước mới không vượt quá viewport
        const maxWidth = window.innerWidth - rect.left - 20
        const maxHeight = window.innerHeight - rect.top - 20

        const newWidth = Math.min(
          Math.max(CONSTANTS.POPUP.MIN_WIDTH, state.startWidth + dx),
          maxWidth
        )
        const newHeight = Math.min(
          Math.max(CONSTANTS.POPUP.MIN_HEIGHT, state.startHeight + dy),
          maxHeight
        )

        popup.style.width = `${newWidth}px`
        popup.style.height = `${newHeight}px`
      }
      const handleMouseUp = () => {
        if (!state.isResizing) return
        state.isResizing = false
        state.originalWidth = popup.offsetWidth
        state.originalHeight = popup.offsetHeight
        state.userHasResized = true
      }
      resizeHandle.addEventListener('mousedown', handleMouseDown)
      document.addEventListener('mousemove', handleMouseMove)
      document.addEventListener('mouseup', handleMouseUp)
    }

    function setupAutoSizeButton(popup, autoSizeBtn) {
      autoSizeBtn.addEventListener('click', () => {
        state.userHasResized = false
        popup.style.width = `${CONSTANTS.POPUP.DEFAULT_WIDTH}px`
        popup.style.height = ''
        popup.style.minWidth = `${CONSTANTS.POPUP.MIN_WIDTH}px`
        popup.style.minHeight = `${CONSTANTS.POPUP.MIN_HEIGHT}px`
        adjustPopupWidth()
        state.originalWidth = popup.offsetWidth
        state.originalHeight = popup.offsetHeight
        window.logToPopup('Popup size reset to auto.')
      })
    }

    function setupToggle(popup, header, toggleBtn, contentWrapper, resizeHandle) {
      toggleBtn.addEventListener('click', () => {
        state.isCollapsed = !state.isCollapsed
        if (state.isCollapsed) {
          // Lưu lại kích thước hiện tại trước khi thu gọn
          state.originalWidth = popup.offsetWidth
          state.originalHeight = popup.offsetHeight

          const collapsedWidth = 350 // px
          const collapsedHeight = header.offsetHeight
          popup.style.height = `${collapsedHeight}px`
          popup.style.width = `${collapsedWidth}px`
          popup.style.minWidth = `${collapsedWidth}px`
          popup.style.minHeight = `${collapsedHeight}px`

          contentWrapper.style.display = 'none'
          resizeHandle.style.display = 'none'
          toggleBtn.textContent = '+'
          toggleBtn.title = 'Expand'
        } else {
          // Khôi phục lại kích thước ban đầu
          popup.style.height = `${
            state.originalHeight || CONSTANTS.POPUP.MIN_HEIGHT
          }px`
          popup.style.width = `${
            state.originalWidth || CONSTANTS.POPUP.DEFAULT_WIDTH
          }px`
          popup.style.minHeight = `${CONSTANTS.POPUP.MIN_HEIGHT}px`
          popup.style.minWidth = `${CONSTANTS.POPUP.MIN_WIDTH}px`

          contentWrapper.style.display = 'flex'
          resizeHandle.style.display = 'block'
          toggleBtn.textContent = '−'
          toggleBtn.title = 'Collapse'
        }
      })
    }

    function setupRefreshButton(refreshButton) {
      refreshButton.addEventListener('click', () => {
        refreshButton.classList.add('spinning')
        refreshData(true) // Force a full refresh
        setTimeout(
          () => refreshButton.classList.remove('spinning'),
          CONSTANTS.ANIMATIONS.SPIN_DURATION
        )
        window.logToPopup('Manual refresh triggered.')
      })
    }

    function setupRefreshIndicator(refreshIndicator, header, refreshButton) {
      refreshIndicator.addEventListener('click', () => {
        // NEW: Handle click during processing to cancel the operation.
        if (state.isProcessingUrls) {
          window.logToPopup('User requested to cancel URL processing.')
          state.cancelProcessing = true
          // The `finally` block in `withRefreshSuspended` will handle the UI
          // and state reset once the current async task finishes/aborts.
          return
        }

        if (state.isPaused) {
          state.isPaused = false
          header.classList.remove('flashing')
          refreshIndicator.textContent = `Auto-refresh in: ${state.timeLeft}s`
          refreshButton.style.display = 'flex'
          window.logToPopup('Auto-refresh resumed.')
        } else {
          state.isPaused = true
          header.classList.add('flashing')
          refreshIndicator.textContent = 'Auto-refresh is paused'
          refreshButton.style.display = 'none'
          window.logToPopup('Auto-refresh paused.')
        }
      })
    }

    function updateColumnSettingsPanel(data = window.homeAwayTableCollectorRawData) {
      if (!window.csvCollectorSettingsPanel || !data) return

      const panel = window.csvCollectorSettingsPanel
      const list = panel._columnList
      const searchInput = panel._columnSearch
      if (!list || !searchInput) return

      const columnMeta = Array.isArray(data.columnMeta) ? data.columnMeta : []
      const selectedKeys = new Set(getVisibleColumnKeys(columnMeta))
      list.innerHTML = ''

      if (!columnMeta.length) {
        list.textContent = 'Refresh data to show columns.'
        return
      }

      columnMeta.forEach((column, index) => {
        const label = document.createElement('label')
        const groupTitle = column.groupTitle || 'General'
        label.dataset.searchText = `${index + 1} ${groupTitle} ${column.header}`.toLowerCase()
        label.style.cssText =
          'display:flex; align-items:center; gap:6px; padding:2px 0; cursor:pointer;'

        const checkbox = document.createElement('input')
        checkbox.type = 'checkbox'
        checkbox.value = column.key
        checkbox.checked = column.required || selectedKeys.has(column.key)
        checkbox.disabled = !!column.required

        const text = document.createElement('span')
        text.textContent = `${groupTitle} / ${column.header}${
          column.required ? ' (fixed)' : ''
        }`

        label.appendChild(checkbox)
        label.appendChild(text)
        list.appendChild(label)
      })

      const applyFilter = () => {
        const query = searchInput.value.trim().toLowerCase()
        list.querySelectorAll('label').forEach((label) => {
          label.style.display = label.dataset.searchText.includes(query)
            ? 'flex'
            : 'none'
        })
      }

      searchInput.oninput = applyFilter
      applyFilter()
    }

    function updateLegacyColumnSettingsPanel(headers = []) {
      if (!window.csvCollectorSettingsPanel) return

      const panel = window.csvCollectorSettingsPanel
      const list = panel._columnList
      const searchInput = panel._columnSearch
      if (!list || !searchInput) return

      list.innerHTML = ''
      const selectedColumns = new Set(getVisibleColumns(headers))
      headers.forEach((header, index) => {
        const isRequired = REQUIRED_VISIBLE_COLUMNS.includes(index)
        const label = document.createElement('label')
        label.dataset.searchText = `${index + 1} ${index} ${header}`.toLowerCase()
        label.style.cssText =
          'display:flex; align-items:center; gap:6px; padding:2px 0; cursor:pointer;'

        const checkbox = document.createElement('input')
        checkbox.type = 'checkbox'
        checkbox.value = String(index)
        checkbox.checked = isRequired || selectedColumns.has(index)
        checkbox.disabled = isRequired

        const text = document.createElement('span')
        text.textContent = `${index + 1}. ${header || `Cột ${index + 1}`}${
          isRequired ? ' (fixed)' : ''
        }`

        label.appendChild(checkbox)
        label.appendChild(text)
        list.appendChild(label)
      })

      const applyFilter = () => {
        const query = searchInput.value.trim().toLowerCase()
        list.querySelectorAll('label').forEach((label) => {
          label.style.display = label.dataset.searchText.includes(query)
            ? 'flex'
            : 'none'
        })
      }

      searchInput.oninput = applyFilter
      applyFilter()
    }

    function updateExtraColumnSettingsPanel() {
      if (!window.csvCollectorSettingsPanel) return

      const panel = window.csvCollectorSettingsPanel
      const list = panel._extraColumnList
      const searchInput = panel._extraColumnSearch
      if (!list || !searchInput) return

      list.innerHTML = ''
      const availableHeaders = state.extraHeaders.filter(
        (key) => !HIDDEN_EXTRA_HEADERS.has(key)
      )
      const selectedHeaders = new Set(getVisibleExtraHeaders())

      if (availableHeaders.length === 0) {
        list.textContent = 'Process URLs to show runtime columns.'
        return
      }

      availableHeaders.forEach((key) => {
        const label = document.createElement('label')
        label.dataset.searchText = key.toLowerCase()
        label.style.cssText =
          'display:flex; align-items:center; gap:6px; padding:2px 0; cursor:pointer;'

        const checkbox = document.createElement('input')
        checkbox.type = 'checkbox'
        checkbox.value = key
        checkbox.checked = selectedHeaders.has(key)

        const text = document.createElement('span')
        text.textContent = key

        label.appendChild(checkbox)
        label.appendChild(text)
        list.appendChild(label)
      })

      const applyFilter = () => {
        const query = searchInput.value.trim().toLowerCase()
        list.querySelectorAll('label').forEach((label) => {
          label.style.display = label.dataset.searchText.includes(query)
            ? 'flex'
            : 'none'
        })
      }

      searchInput.oninput = applyFilter
      applyFilter()
    }

    function updateLeagueFilterPanel(data = []) {
      if (!window.csvCollectorSettingsPanel || !data || data.length === 0) return

      const panel = window.csvCollectorSettingsPanel
      const list = panel._leagueList
      const searchInput = panel._leagueSearch
      if (!list || !searchInput) return

      const counts = new Map()
      data.slice(1).forEach((row) => {
        const league = normalizeLeague(row[CSV_COLUMNS.LEAGUE]) || '(blank)'
        counts.set(league, (counts.get(league) || 0) + 1)
      })

      const leagues = Array.from(counts.keys()).sort((a, b) =>
        a.localeCompare(b)
      )
      const selectedLeagues = Array.isArray(settings.selectedLeagues)
        ? new Set(settings.selectedLeagues.map(normalizeLeague))
        : null

      list.innerHTML = ''
      if (leagues.length === 0) {
        list.textContent = 'Load CSV to show leagues.'
        return
      }

      leagues.forEach((league) => {
        const label = document.createElement('label')
        label.dataset.searchText = league.toLowerCase()
        label.style.cssText =
          'display:flex; align-items:center; gap:6px; padding:2px 0; cursor:pointer;'

        const checkbox = document.createElement('input')
        checkbox.type = 'checkbox'
        checkbox.value = league
        checkbox.checked = !selectedLeagues || selectedLeagues.has(league)

        const text = document.createElement('span')
        text.textContent = `${league} (${counts.get(league)})`

        label.appendChild(checkbox)
        label.appendChild(text)
        list.appendChild(label)
      })

      const applyFilter = () => {
        const query = searchInput.value.trim().toLowerCase()
        list.querySelectorAll('label').forEach((label) => {
          label.style.display = label.dataset.searchText.includes(query)
            ? 'flex'
            : 'none'
        })
      }

      searchInput.oninput = applyFilter
      applyFilter()
    }

    function createSettingsBackdrop() {
      const backdrop = document.createElement('div')
      backdrop.style.cssText = `position: fixed; inset: 0; z-index: ${
        CONSTANTS.Z_INDEX + 1
      }; background: rgba(0,0,0,0.08); display: none;`
      return backdrop
    }

    function createSettingsPanel() {
      const panel = document.createElement('div')
      panel.style.cssText = `
        position: fixed; top: 60px; left: 20px; background: white;
        border: 1px solid ${CONSTANTS.COLORS.BORDER}; box-shadow: 0 2px 8px rgba(0,0,0,0.25);
        border-radius: 4px; z-index: ${CONSTANTS.Z_INDEX + 2}; width: min(360px, calc(100vw - 40px));
        max-height: calc(100vh - 120px); overflow: hidden; flex-direction: column;
        display: none; font-size: 12px;`

      const panelBody = document.createElement('div')
      panelBody.style.cssText = 'padding: 10px; overflow: auto; min-height: 0;'

      const field = (labelText, initValue, id) => {
        const row = document.createElement('div')
        row.style.cssText =
          'display: flex; align-items: center; justify-content: space-between; margin: 6px 0; gap: 8px;'
        const label = document.createElement('label')
        label.textContent = labelText
        label.setAttribute('for', id)
        const input = document.createElement('input')
        input.type = 'number'
        input.min = '0.5'
        input.step = 'any'
        input.value = String(initValue)
        input.id = id
        input.style.cssText = 'width: 70px; padding: 2px 4px;'
        row.appendChild(label)
        row.appendChild(input)
        return { row, input }
      }

      const noData = field('No data interval (s)', settings.noDataInterval, 'hatc-no-data')
      const hasData = field('Data found interval (s)', settings.dataFoundInterval, 'hatc-has-data')
      const defInt = field('Default interval (s)', settings.defaultInterval, 'hatc-default')
      panelBody.appendChild(noData.row)
      panelBody.appendChild(hasData.row)
      panelBody.appendChild(defInt.row)

      const columnSection = document.createElement('div')
      columnSection.style.cssText = `margin-top: 10px; padding-top: 8px; border-top: 1px solid ${CONSTANTS.COLORS.BORDER};`
      const columnTitle = document.createElement('div')
      columnTitle.textContent = 'Visible columns'
      columnTitle.style.cssText = 'font-weight: bold; margin-bottom: 6px;'
      const columnSearch = document.createElement('input')
      columnSearch.type = 'search'
      columnSearch.placeholder = 'Search column...'
      columnSearch.style.cssText =
        'width: 100%; box-sizing: border-box; padding: 3px 5px; margin-bottom: 6px;'

      const columnActions = document.createElement('div')
      columnActions.style.cssText =
        'display: flex; gap: 6px; margin-bottom: 6px; flex-wrap: wrap;'
      const selectAll = document.createElement('button')
      selectAll.textContent = 'All'
      const clearColumns = document.createElement('button')
      clearColumns.textContent = 'Clear'
      columnActions.appendChild(selectAll)
      columnActions.appendChild(clearColumns)

      const columnList = document.createElement('div')
      columnList.style.cssText = `max-height: 260px; overflow: auto; border: 1px solid ${CONSTANTS.COLORS.BORDER}; padding: 6px; background: #fff;`
      columnList.textContent = 'Refresh data to show columns.'

      columnSection.appendChild(columnTitle)
      columnSection.appendChild(columnSearch)
      columnSection.appendChild(columnActions)
      columnSection.appendChild(columnList)
      panelBody.appendChild(columnSection)
      panel.appendChild(panelBody)

      const actions = document.createElement('div')
      actions.style.cssText = `padding: 8px 10px; display: flex; justify-content: flex-end; gap: 8px; border-top: 1px solid ${CONSTANTS.COLORS.BORDER}; background: white; flex-shrink: 0;`
      const cancel = document.createElement('button')
      cancel.textContent = 'Cancel'
      const save = document.createElement('button')
      save.textContent = 'Save'
      actions.appendChild(cancel)
      actions.appendChild(save)
      panel.appendChild(actions)

      panel._inputs = { noData, hasData, defInt }
      panel._buttons = { cancel, save, selectAll, clearColumns }
      panel._columnList = columnList
      panel._columnSearch = columnSearch
      return panel
    }

    function positionSettingsPanel(panel, popup) {
      const width = Math.min(760, window.innerWidth - 40)
      const maxHeight = Math.max(160, window.innerHeight - 40)
      const left = Math.max(20, (window.innerWidth - width) / 2)
      const top = Math.max(20, (window.innerHeight - maxHeight) / 2)

      panel.style.width = `${width}px`
      panel.style.left = `${left}px`
      panel.style.top = `${top}px`
      panel.style.maxHeight = `${maxHeight}px`
    }

    function setupSettingsInteractions(settingsBtn, panel, popup, backdrop) {
      const close = () => {
        panel.style.display = 'none'
        backdrop.style.display = 'none'
      }
      settingsBtn.addEventListener('click', () => {
        if (panel.style.display === 'none') {
          positionSettingsPanel(panel, popup)
          backdrop.style.display = 'block'
          panel.style.display = 'flex'
        } else {
          close()
        }
      })
      backdrop.addEventListener('click', close)
      window.addEventListener('resize', () => {
        if (panel.style.display !== 'none') positionSettingsPanel(panel, popup)
      })
      panel._buttons.cancel.addEventListener('click', close)
      panel._buttons.selectAll.addEventListener('click', () => {
        settings.visibleColumns = null
        updateColumnSettingsPanel(window.homeAwayTableCollectorRawData)
        panel._columnList
          .querySelectorAll("input[type='checkbox']")
          .forEach((checkbox) => {
            checkbox.checked = true
          })
      })
      panel._buttons.clearColumns.addEventListener('click', () => {
        panel._columnList
          .querySelectorAll("input[type='checkbox']")
          .forEach((checkbox) => {
            checkbox.checked = checkbox.disabled
          })
      })
      panel._buttons.save.addEventListener('click', () => {
        const newNoData = parseFloat(panel._inputs.noData.input.value)
        if (!isNaN(newNoData)) settings.noDataInterval = Math.max(0.5, newNoData)

        const newHasData = parseFloat(panel._inputs.hasData.input.value)
        if (!isNaN(newHasData)) settings.dataFoundInterval = Math.max(0.5, newHasData)

        const newDefInt = parseFloat(panel._inputs.defInt.input.value)
        if (!isNaN(newDefInt)) settings.defaultInterval = Math.max(0.5, newDefInt)

        const selectedColumns = Array.from(
          panel._columnList.querySelectorAll("input[type='checkbox']:checked")
        ).map((checkbox) => checkbox.value)
        if (panel._columnList.querySelectorAll("input[type='checkbox']").length) {
          settings.visibleColumns = selectedColumns
        }

        saveSettings(settings)

        if (window.homeAwayTableCollectorRawData && window.csvCollectorTbody) {
          updateColumnSettingsPanel(window.homeAwayTableCollectorRawData)
          const visibleData = filterExtractedDataColumns(
            window.homeAwayTableCollectorRawData
          )
          window.homeAwayTableCollectorLastData = visibleData
          updateTableWithData(
            visibleData,
            window.csvCollectorTbody,
            true
          )
        }

        updateRefreshInterval(state.lastRecordCount || 0)
        if (!state.isPaused) {
          state.timeLeft = state.currentInterval
          if (window.csvCollectorRefreshIndicator) {
            window.csvCollectorRefreshIndicator.textContent = `Auto-refresh in: ${state.timeLeft}s`
          }
        }
        window.logToPopup('Settings saved.')
        close()
      })
    }

    function createTable() {
      const table = document.createElement('table')
      table.style.cssText = `width: 100%; border-collapse: collapse; font-size: 12px;`
      table.appendChild(document.createElement('thead'))
      table.appendChild(document.createElement('tbody'))
      return table
    }

    function injectStyles() {
      if (document.getElementById('csv-collector-styles')) return
      const style = document.createElement('style')
      style.id = 'csv-collector-styles'
      style.textContent = `
        #csv-collector-popup .spinning { animation: cc-spin 1s linear infinite; }
        @keyframes cc-spin { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }
        #csv-collector-popup .flashing { animation: cc-flash 1s infinite alternate; }
        @keyframes cc-flash { from { filter: brightness(1); } to { filter: brightness(1.2); } }
      `
      document.head.appendChild(style)
    }

    function createFloatingPopup() {
      injectStyles()
      const popup = document.createElement('div')
      popup.id = 'csv-collector-popup'
      popup.style.cssText = `
        position: fixed; top: 70px; left: 20px; width: ${CONSTANTS.POPUP.DEFAULT_WIDTH}px;
        min-width: ${CONSTANTS.POPUP.MIN_WIDTH}px; max-width: calc(100vw - 20px - 20px);
        max-height: calc(100vh - 70px - 20px); background: ${CONSTANTS.COLORS.BACKGROUND};
        border: 1px solid ${CONSTANTS.COLORS.BORDER}; border-radius: 4px;
        box-shadow: 0 2px 10px rgba(0,0,0,0.1); z-index: ${CONSTANTS.Z_INDEX}; display: flex;
        flex-direction: column; overflow: hidden;`

      const header = document.createElement('div')
      header.style.cssText = `
        padding: 8px; background: linear-gradient(to right, ${CONSTANTS.COLORS.HEADER_GRADIENT_START}, ${CONSTANTS.COLORS.HEADER_GRADIENT_END});
        border-bottom: 1px solid ${CONSTANTS.COLORS.BORDER}; cursor: move; display: flex;
        justify-content: space-between; align-items: center; user-select: none;
        height: ${CONSTANTS.POPUP.HEADER_HEIGHT}px; color: white;`

      const titleContainer = document.createElement('div')
      titleContainer.className = 'title-container'
      titleContainer.style.cssText = `display: flex; align-items: center; gap: 8px;`
      const title = document.createElement('span')
      title.textContent = 'Home/Away Table Collector'
      title.style.fontWeight = 'bold'
      titleContainer.appendChild(title)

      const controlsContainer = document.createElement('div')
      controlsContainer.style.cssText = `display: flex; align-items: center; gap: 12px;`

      const refreshIndicator = document.createElement('span')
      refreshIndicator.style.cssText = `font-size: 12px; color: #e0e0e0; cursor: pointer;`
      const refreshButton = document.createElement('button')
      refreshButton.innerHTML = '↻'
      refreshButton.title = 'Refresh now'
      refreshButton.style.cssText = `background: none; border: none; color: white; cursor: pointer; font-size: 16px;`
      const settingsBtn = document.createElement('button')
      settingsBtn.textContent = '⚙️'
      settingsBtn.title = 'Settings'
      settingsBtn.style.cssText = `background: none; border: none; color: white; cursor: pointer; font-size: 16px;`
      const autoSizeBtn = document.createElement('button')
      autoSizeBtn.textContent = '⤢'
      autoSizeBtn.title = 'Reset popup size to auto'
      autoSizeBtn.style.cssText = `background: none; border: none; color: white; cursor: pointer; font-size: 16px;`
      const toggleBtn = document.createElement('button')
      toggleBtn.textContent = '−'
      toggleBtn.title = 'Collapse'
      toggleBtn.style.cssText = `background: none; border: none; color: white; cursor: pointer; font-size: 18px;`

      controlsContainer.appendChild(refreshIndicator)
      controlsContainer.appendChild(refreshButton)
      controlsContainer.appendChild(settingsBtn)
      controlsContainer.appendChild(autoSizeBtn)
      controlsContainer.appendChild(toggleBtn)
      header.appendChild(titleContainer)
      header.appendChild(controlsContainer)

      const contentWrapper = document.createElement('div')
      contentWrapper.style.cssText = `flex: 1; display: flex; flex-direction: column; min-height: 0; overflow: hidden;`
      const mainContent = document.createElement('div')
      mainContent.style.cssText = `flex: 1; padding: 10px; overflow: auto; min-height: 0;`
      const table = createTable()
      mainContent.appendChild(table)

      // Controls bar between table and log (checkbox + gripper for resize)
      const controlsBar = document.createElement('div')
      controlsBar.style.cssText = `
        display: flex;
        align-items: center;
        justify-content: space-between;
        padding: 4px 10px;
        border-top: 1px solid ${CONSTANTS.COLORS.BORDER};
        border-bottom: 1px solid ${CONSTANTS.COLORS.BORDER};
        background: ${CONSTANTS.COLORS.HEADER_BACKGROUND};
        user-select: none;
        gap: 8px;
        flex-wrap: nowrap;
        min-height: 26px;
      `
      const autoScrollWrap = document.createElement('label')
      autoScrollWrap.style.cssText =
        'display:flex; align-items:center; gap:6px; cursor:pointer; white-space: nowrap;'
      const autoScrollCheckbox = document.createElement('input')
      autoScrollCheckbox.type = 'checkbox'
      autoScrollCheckbox.checked = true
      const autoScrollText = document.createElement('span')
      autoScrollText.textContent = 'Auto-scroll log'
      autoScrollText.style.cssText = 'white-space: nowrap;'
      autoScrollWrap.appendChild(autoScrollCheckbox)
      autoScrollWrap.appendChild(autoScrollText)

      const gripper = document.createElement('div')
      gripper.textContent = '⋮⋮'
      gripper.title = 'Drag to resize log height'
      gripper.style.cssText =
        'cursor: row-resize; padding: 0 6px; color:#666; height: 18px; display:flex; align-items:center;'

      controlsBar.appendChild(autoScrollWrap)
      controlsBar.appendChild(gripper)

      const logArea = document.createElement('textarea')
      logArea.style.cssText = `height: 80px; margin: 0 10px 10px 10px; padding: 5px; border: 1px solid ${CONSTANTS.COLORS.BORDER}; resize: none; flex-shrink: 0;`
      logArea.readOnly = true

      // Auto-scroll toggle
      autoScrollCheckbox.addEventListener('change', () => {
        state.autoScrollLog = !!autoScrollCheckbox.checked
      })

      // Drag to resize log height
      ;(function setupInnerResize() {
        let resizing = false
        let startY = 0
        let startHeight = 0
        const minLogHeight = 40
        function onDown(e) {
          if (e.target === autoScrollCheckbox || e.target === autoScrollText)
            return
          e.preventDefault()
          resizing = true
          startY = e.clientY
          startHeight = logArea.offsetHeight
          window.addEventListener('mousemove', onMove)
          window.addEventListener('mouseup', onUp)
        }
        function onMove(e) {
          if (!resizing) return
          const delta = startY - e.clientY // Drag up increases height
          const wrapperRect = contentWrapper.getBoundingClientRect()
          const maxLogHeight = Math.max(minLogHeight, wrapperRect.height - 100) // Reserve space for table
          const newHeight = Math.min(
            Math.max(minLogHeight, startHeight + delta),
            maxLogHeight
          )
          logArea.style.height = newHeight + 'px'
        }
        function onUp() {
          if (!resizing) return
          resizing = false
          window.removeEventListener('mousemove', onMove)
          window.removeEventListener('mouseup', onUp)
        }
        // Allow dragging from gripper or the whole bar
        gripper.addEventListener('mousedown', onDown)
        controlsBar.addEventListener('mousedown', (e) => {
          if (e.target === autoScrollCheckbox || e.target === autoScrollText)
            return
          onDown(e)
        })
      })()

      contentWrapper.appendChild(mainContent)
      contentWrapper.appendChild(controlsBar)
      contentWrapper.appendChild(logArea)

      const resizeHandle = document.createElement('div')
      resizeHandle.style.cssText = `position: absolute; right: 0; bottom: 0; width: 16px; height: 16px; cursor: se-resize; z-index: 1; background: linear-gradient(135deg, transparent 50%, rgba(0,0,0,0.25) 50%);`

      const settingsBackdrop = createSettingsBackdrop()
      const settingsPanel = createSettingsPanel()
      window.csvCollectorSettingsBackdrop = settingsBackdrop
      window.csvCollectorSettingsPanel = settingsPanel

      popup.appendChild(header)
      popup.appendChild(contentWrapper)
      popup.appendChild(resizeHandle)

      // Store references on window
      window.csvCollectorTbody = table.querySelector('tbody')
      window.csvCollectorRefreshIndicator = refreshIndicator
      window.logToPopup = (message) => {
        const timestamp = new Date().toLocaleTimeString()
        const lines = logArea.value ? logArea.value.split('\n') : []
        if (lines[lines.length - 1] === '') lines.pop()
        lines.push(`[${timestamp}] ${message}`)
        if (lines.length > CONSTANTS.LOG.MAX_LINES) {
          lines.splice(0, lines.length - CONSTANTS.LOG.MAX_LINES)
        }
        logArea.value = `${lines.join('\n')}\n`
        if (state.autoScrollLog) {
          logArea.scrollTop = logArea.scrollHeight
        }
      }

      // Setup interactions
      setupDragAndDrop(popup, header)
      setupResize(popup, resizeHandle)
      setupAutoSizeButton(popup, autoSizeBtn)
      setupToggle(popup, header, toggleBtn, contentWrapper, resizeHandle)
      setupRefreshButton(refreshButton)
      setupRefreshIndicator(refreshIndicator, header, refreshButton)
      setupSettingsInteractions(settingsBtn, settingsPanel, popup, settingsBackdrop)

      state.originalHeight = popup.offsetHeight
      return popup
    }

    // ==================== INITIALIZATION ====================
    window.addEventListener('load', () => {
      try {
        const popup = createFloatingPopup()
        document.body.appendChild(popup)
        if (window.csvCollectorSettingsBackdrop) {
          document.body.appendChild(window.csvCollectorSettingsBackdrop)
        }
        if (window.csvCollectorSettingsPanel) {
          document.body.appendChild(window.csvCollectorSettingsPanel)
        }
        window.logToPopup('Home/Away Table Collector initialized.')

        refreshData()
        startRefreshInterval()
      } catch (error) {
        console.error('Home/Away Table Collector: Fatal error on initialization:', error)
      }
    })
  } catch (error) {
    console.error('Home/Away Table Collector: Fatal error in script:', error)
  }

})()
